// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://siifpdmqmoyxjymrkrws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpaWZwZG1xbW95eGp5bXJrcndzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNDgwMTksImV4cCI6MjA2ODYyNDAxOX0.W1NwlStW0MihxRkf2OSWii9WtY_p2ESf5u-Lhv9lVxQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});